<?php
/**
 * @file
 * theme_semester_course_entity.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function theme_semester_course_entity_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_node_info().
 */
function theme_semester_course_entity_node_info() {
  $items = array(
    'course' => array(
      'name' => t('Course'),
      'base' => 'node_content',
      'description' => t('A <em>Course</em> that relates to the theme of the semester.'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
